language: node_js
node_js:
  - "stable"
script:
  - echo "Stated deployment..."
  - echo "Installing dependencies..."
  - npm i
  - echo "Building project..."
  - npm run build
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token "$FIREBASE_TOKEN"
